function T = initResultTable(labels)
    n = numel(labels);
    T = table(uint16(labels'), zeros(n,1), zeros(n,1), zeros(n,1), ...
              zeros(n,1), zeros(n,1), zeros(n,1), zeros(n,1), ...
              'VariableNames', {'LabelNumber','LabelVolume','PlaqueVolume','NonPlaqueVolume', ...
                                'PlaqueValueInMRI','PlaqueValueInLowrank', ...
                                'NonPlaqueValueInMRI','NonPlaqueValueInLowrank'});
end